include:
  - remote: https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/main/.gitlab-ci/docker-ros.yml

variables:
  PLATFORM: amd64
  TARGET: dev,run
  BASE_IMAGE: gitlab.ika.rwth-aachen.de:5050/fb-fi/its-modules/monitoring/ros-monitoring:latest
  COMMAND: ros2 launch ros_middleware_bridge ros_middleware_bridge_launch.py
