services:

  ros-middleware-bridge:
    image: ghcr.io/openads-project/ros_middleware_bridge:v1.1.0
    environment:
      # --- name ------
      NAMESPACE: /
      NAME: ros_middleware_bridge
      # --- side a ---
      SIDE_A_NAME: ${SIDE_A_NAME:-bridge_fast}
      SIDE_A_RMW_IMPLEMENTATION: ${SIDE_A_RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
      SIDE_A_TX_PORT: ${SIDE_A_TX_PORT:-17001}
      SIDE_A_RX_PORT: ${SIDE_A_RX_PORT:-17002}
      # --- side b ---
      SIDE_B_NAME: ${SIDE_B_NAME:-bridge_zenoh}
      SIDE_B_RMW_IMPLEMENTATION: ${SIDE_B_RMW_IMPLEMENTATION:-rmw_zenoh_cpp}
      SIDE_B_TX_PORT: ${SIDE_B_TX_PORT:-17002}
      SIDE_B_RX_PORT: ${SIDE_B_RX_PORT:-17001}
      # --- other -----
      LOG_LEVEL: ${LOG_LEVEL:-info}
      USE_SIM_TIME: ${USE_SIM_TIME:-false}
      PARAMS: ${PARAMS:-/docker-ros/ws/install/ros_middleware_bridge/share/ros_middleware_bridge/config/params.yml}
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch ros_middleware_bridge ros_middleware_bridge.launch.py \
          namespace:=$${NAMESPACE} \
          log_level:=$${LOG_LEVEL} \
          use_sim_time:=$${USE_SIM_TIME} \
          params:=$${PARAMS} \
          side_a_name:=$${SIDE_A_NAME} \
          side_a_rmw_implementation:=$${SIDE_A_RMW_IMPLEMENTATION} \
          side_a_tx_port:=$${SIDE_A_TX_PORT} \
          side_a_rx_port:=$${SIDE_A_RX_PORT} \
          side_b_name:=$${SIDE_B_NAME} \
          side_b_rmw_implementation:=$${SIDE_B_RMW_IMPLEMENTATION} \
          side_b_tx_port:=$${SIDE_B_TX_PORT} \
          side_b_rx_port:=$${SIDE_B_RX_PORT}
