/**:
  ros__parameters:
    num_threads: 2
    remote_host: 127.0.0.1
    socket_buffer_bytes: 1048576
    dds2zenoh.topics:
      - /carla/ego_vehicle/karl_rack_cameras/camera_front_center/image
      - /carla/ego_vehicle/imu
      - /carla/ego_vehicle/gnss
      - /carla/ego_vehicle/lidar_front/point_cloud
      - /carla/ego_vehicle/rgb_view/image
      - /clock
    dds2zenoh.topic_types:
      - sensor_msgs/msg/Image
      - sensor_msgs/msg/Imu
      - sensor_msgs/msg/NavSatFix
      - sensor_msgs/msg/PointCloud2
      - sensor_msgs/msg/Image
      - rosgraph_msgs/msg/Clock
    dds2zenoh.qos_depths:
      - 10
    zenoh2dds.topics:
      - /carla/ego_vehicle/vehicle_control_cmd
    zenoh2dds.topic_types:
      - carla_msgs/msg/CarlaEgoVehicleControl
    zenoh2dds.qos_depths:
      - 10

bridge_fast:
  ros__parameters:
    bridge_role: dds
    tx_port: 17001
    rx_port: 17002

bridge_zenoh:
  ros__parameters:
    bridge_role: zenoh
    tx_port: 17002
    rx_port: 17001
