/**:
  ros__parameters:
    num_threads: 8
    remote_host: 127.0.0.1
    shm_namespace: ros_middleware_bridge
    socket_buffer_bytes: 1048576
    max_udp_payload_bytes: 60000
    max_shm_message_bytes: 50331648  # 48 MiB as default in 'rmw_zenoh'
    shm_poll_interval_us: 1000
    reassembly_timeout_ms: 1000
    auto_discovery_wait_ms: 1000
    auto_discovery_poll_ms: 1000
    # Generic example routes (replace with your own topics/types).
    side_a2b.topics:
      - /bridge/input_string
    side_a2b.topic_types:
      - std_msgs/msg/String
    side_a2b.transports:
      - udp
    side_a2b.qos_depths:
      - 10
    side_b2a.topics:
      - /bridge/output_string
      - /bridge/output_image
    side_b2a.topic_types:
      - std_msgs/msg/String
      - sensor_msgs/msg/Image
    side_b2a.transports:
      - udp
      - shm
    side_b2a.qos_depths:
      - 10
      - 5
